//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRHUB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Employee_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ResetCode { get; set; }
        public string Token { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public string Captcha { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
