//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRHUB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Designation_History> Designation_History { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<Leave_Tracking> Leave_Tracking { get; set; }
        public virtual DbSet<Leave_Type> Leave_Type { get; set; }
    
        public virtual int AddUserInfo(Nullable<long> empid, string empUserName, string emppass)
        {
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(long));
    
            var empUserNameParameter = empUserName != null ?
                new ObjectParameter("empUserName", empUserName) :
                new ObjectParameter("empUserName", typeof(string));
    
            var emppassParameter = emppass != null ?
                new ObjectParameter("emppass", emppass) :
                new ObjectParameter("emppass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUserInfo", empidParameter, empUserNameParameter, emppassParameter);
        }
    
        public virtual int LeaveEntryForNew(Nullable<System.DateTime> dOJ, Nullable<int> empid)
        {
            var dOJParameter = dOJ.HasValue ?
                new ObjectParameter("DOJ", dOJ) :
                new ObjectParameter("DOJ", typeof(System.DateTime));
    
            var empidParameter = empid.HasValue ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LeaveEntryForNew", dOJParameter, empidParameter);
        }
    }
}
